### PR TITLE
Rearrange level exercises towards a particular progression

### PR DESCRIPTION
**Pull request by mankyKitty**
Shuffling commands around based on the following concept for new level structure:

- [x] Lens Cheatsheet:
  - [x] View
  - [x] Set/Over
- [x] Prisms:
  - [x] preview
  - [x] review
- [x] Composition 

Level01 - "Introduction, setup etc":

- [x] Three separate commands (cSetDrinkCoffee, cSetDrinkHotChocolate, cSetDrinkTea)

Level02 - "Pre-conditions, commands with arguments":

- [x] (Commands with args) - Collapse set drink type commands to cSetDrinkType
- [x] (Preconditions) - cAddMug, cTakeMug
- [x] level readme

Level03 - "More commands!":

- [x] (Expansion of model / practice) - cInsertCoins, cRefundCoins
- [x] (args & preconditions practice) - cAddMilkSugar
- [x] level readme

Level04 - "Positive / Negative Testing":

- [x] Implement happy/sad versions of commands
- [x] discussions about why this matters
- [x] level readme

Level05 - "Phases and keeping your model sane":

- [x] discuss and implement cCheckCredit
- [x] implement cDispenseHappy
- [x] level readme

An extension to provide more exercises is to have an open ended assignment to implement a connected ordering system so the machine never runs out of coffee/additives etc. #showerthought

### CODE REVIEW

**Comment by endgame** [comment]
I'm reading your summary and not the actual changes. Whether we do the ugly thing and then lensify it really depends on whether we want to assume lens knowledge for the workshop. (And how much - there's a huge range within the "knowing lens" space.)

**Comment by mankyKitty** [comment]
We might just have to suck it and see. Although if we used lenses as a matter of course *BUT* we provide a "cheatsheet" as well as be willing to stop and explain. Coupled with keeping ourselves in check WRT staying away from the dark and woolly lens things. That should be enough?

**Comment by endgame** [comment]
A "lens in thirty seconds" sidebar would work, if you're just using view/set/over and composition. What lensy stuff do you want?

**Comment by mankyKitty** [comment]
At the moment I think that would cover everything. I was wondering about the possible use of Prisms as patterns for later on, but that can probably be an "exercise for the reader".

Alright, I'll floop that level TODO to be a cheatsheet. :+1:

**Comment by benkolera** [comment]
FWIW, @dalaing puts lensy stuff in his reflex workshop and I can't remember hearing that the world was ending at either run of the workshop. :slightly_smiling_face:

**Comment by mankyKitty** [comment]
Feel free to start looking at the actual content in this PR, things are in place and I'm fleshing out readmes.

The lens cheatsheet is woeful, but started at least.. Ahem

**Pull request merged**
